sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t egatskalov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true egatskalov/docker-react npm run test -- --coverage


